config/routes.rb
MessageBoard::Application.routes.draw do
	
	resources :users, :categories, :admins
	resources :sessions, olny: [:new, :create, :destroy]
	resources :ads, :except => [:index, :show]

	match "/admin:page", to: 'ads#admin'
	match "/admin", to: 'ads#admin'
	match "ads/:id", to: 'ads#destroy'
  match "/signup", to: 'users#new'	
	match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
	match 'ads:page', to: 'ads#index'
	match 'category:id', to: 'ads#get_category'
	
	
	root :to => 'ads#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
	belongs_to :categories
	
	attr_accessible :title, :content, :category_id, :city, :address, :email
	
	email_regex = /^[-a-z0-9!#$&'*+=?^_`{|}~]+(\.[-a-z0-9!#$&'*+=?^_`{|}~]+)*@([a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?\.)*(aero|arpa|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|[a-z][a-z])$/i
	
	validates :category_id, presence: true
	
	validates :title, presence: true,
										length: { maximum: 25 }
										
	validates :content, presence: true,
											length: { maximum: 140 }
											
	validates :email, presence: true,
										format: { with: email_regex }		

	validates :city, presence: true,
										length: { maximum: 25 }

	validates :address, presence: true,
										length: { maximum: 35 }									
	
	PerPage = 3
  def self.page(pg)
    pg = pg.to_i
    self.order('id desc').offset((pg-1)*PerPage).limit(PerPage)
  end
 
  def self.pgcount
    count % PerPage == 0 ? count / PerPage : count / PerPage + 1
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name
	
	has_many :ads, dependent: :destroy
	
	validates :name, presence: true, length: { maximum: 25 }
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation, :admin
	
	email_regex = /^[-a-z0-9!#$&'*+=?^_`{|}~]+(\.[-a-z0-9!#$&'*+=?^_`{|}~]+)*@([a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?\.)*(aero|arpa|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|[a-z][a-z])$/i
	
	validates :name, presence: true,
									 length: { maximum: 50 }
									 
	validates :email, presence: true,
										uniqueness: { case_sensitive: false },
										format: { with: email_regex }
										
	validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }		

	before_save :encrypt_password
	
	def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

	def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
	
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end								 
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

	def new
		@ad = Ad.new
		@cats = Category.all
		@title = 'New ad'
	end
	
	def create
		@ad = Ad.new(params[:ad])
		if @ad.save
			if !admin?
				redirect_to '/admin'
			else	
				redirect_to root_path
			end	
		end	
	end

  def index
		@title = 'All ads'
		@ads_per_page = Ad.page(params[:page])
		@cats = Category.all
  end
	
	def destroy
		Ad.find(params[:id]).destroy
		if !admin?
			redirect_to '/admin'
		else	
			redirect_to root_path
		end	
	end
	
	def edit
		@ad = Ad.find(params[:id])
		@cats = Category.all
		@title = 'Edit ad'
	end
	
	def update
		@ad = Ad.find(params[:id])
		if @ad.update_attributes(params[:ad])
			if !admin?
				redirect_to '/admin'
			else	
				redirect_to root_path
			end	
		else
			render 'edit'
		end
	end
	
	def admin
		admin?
		@ads_per_page = Ad.page(params[:page])
		@cats = get_categories
	end
	
	def get_category
		@cats = Category.all
		@cat = Category.find(params[:id])
		@ads_by_cat = @cat.ads.all
		@title = @cat.name
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include SessionsHelper
	include AdsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
		@title = 'Sign in'
  end
	
	def create
		user = User.authenticate(params[:session][:email],
                           params[:session][:password])
		if user.nil?
			@title = "Sign in"
      render 'new'
		else
			sign_in user
      redirect_to root_path
		end
	end
	
	def destroy
		sign_out
    redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
		@user = User.new
		@title = 'Sign up'
	end	
	
	def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_path
    else
      @title = "Sign up"
      render 'new'
    end
  end
	
end

app/helpers/ads_helper.rb
module AdsHelper

	def root
		current_user.admin == true
	end
	
	def admin?
		if !signed_in?
			redirect_to root_path
		else
			if !root
				redirect_to root_path
			end
		end	
	end
	
	def get_categories
		Category.all
	end
	
	def pp_name(check)
		if check == true
			return 'admin'
		else
			return 'ads'
		end	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title
		base_title = "Message board"
		if @title.nil?
			base_title
		else
			"#{base_title} - #{@title}"
		end
	end
	
	def logo
		image_tag('news.png', alt: 'News', class: 'image')
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
	
	def current_user=(user)
    @current_user = user
  end
	
	def current_user
    @current_user ||= user_from_remember_token
  end
	
	def signed_in?
    !current_user.nil?
  end
	
	def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
	
	private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ads/admin.html.erb
<%= render 'layouts/get_categories' %>

<% @check = true %>
<%= render 'layouts/all_ads' %>

app/views/ads/edit.html.erb
<section id = "con">

	<h1>Edit ad</h1>

	<%= render 'layouts/form' %>
	
</section>

app/views/ads/get_category.html.erb
<%= render 'layouts/get_categories' %>


<section id = "con">
	<h2><%= @cat.name %></h2>
	<% @check = true %>
	<% @ads_by_cat.each do |ad|%>
		<p><%=  "#{ad.title} - #{ad.content}" %>
		<% if @check == true %>
			<%= link_to 'edit', edit_ad_path(ad) %>
			<%= link_to 'delete', { controller: :ads, :action => :destroy, :id => ad.id }, method: :delete, confirm: 'Are u sure?'%></p>
		<% end %>	
		</p>
	<% end %>

</section>

app/views/ads/index.html.erb
<%= render 'layouts/get_categories' %>

<%= render 'layouts/all_ads' %>

app/views/ads/new.html.erb
<section id = 'con'>

	<h2>Add an ad</h2>
	
	<%= render 'layouts/form' %>
	
</section>

app/views/categories/show.html.erb
<section id = "cat">
<% @cats.each do |cat| %>
	<p><%= link_to "#{cat.name}", category_path(cat) %></p>
<% end %>
</section>
<section id = "con">
<h2><% @ads_by_cat.each do |ad|%>
<p><%=  "#{ad.title} - #{ad.content}" %></p>
<% end %></h2>
</section>

app/views/layouts/_ads_by_category.html.erb
<section id = "cat">

	<% @cats.each do |cat| %>
		<p><%= link_to "#{cat.name}", "category#{cat.id}" %></p>
	<% end %>

</section>

app/views/layouts/_all_ads.html.erb
<section id = "con">

	<h2>Ads</h2>

	<% @ads_per_page.each do |ad|%>
		<p><%= "#{ad[:title]} - #{ad[:email]} - #{ad[:city]} - #{ad[:address]}" %></p>
		<p><%= "#{ad[:content]}" %>
		<% if @check == true %>
			<span id = "adm"><%= link_to 'edit', edit_ad_path(ad) %>
			<%= link_to 'delete', { controller: :ads, :action => :destroy, :id => ad.id }, method: :delete, confirm: 'Are u sure?'%></span></p>
		<% end %>	
		</p>
	<% end %>
	
	<% Ad.pgcount.times do |p|%>
		<%= link_to p+1, "/#{pp_name(@check)}#{p+1}" %>
	<% end %>

</section>

app/views/layouts/_form.html.erb
<%= form_for @ad do |f| %>
	
		<p><%= f.label :title %></p>
		<p><%= f.text_field :title %></p>
		
		<p><%= f.label :email %></p>
		<p><%= f.text_field :email %></p>
		
		<p><%= f.label :city %></p>
		<p><%= f.text_field :city %></p>
		
		<p><%= f.label :address %></p>
		<p><%= f.text_field :address %></p>
		
		<p><%= f.label :content %></p>
		<p><%= f.text_area :content %></p>
		
		<p>Choose category of your ad</p>
		<p><%= f.select(:category_id, options_for_select(@cats.collect {|p| [ p.name, p.id ] },   "Select Category")) %></p>
		
		<%= f.submit %>
	<% end %>

app/views/layouts/_get_categories.html.erb
<section id = "cat">

	<% @cats.each do |cat| %>
		<p><%= link_to "#{cat.name}", "category#{cat.id}" %></p>
	<% end %>

</section>

app/views/layouts/_header.html.erb
<header>
			<%= link_to logo, root_path %>
			<nav>
				<%= link_to 'Home', root_path %>
				<% if signed_in? %>
					<%= link_to 'Add ad', new_ad_path %>
					<%= link_to "Sign out", signout_path, :method => :delete %>
					<% if  root%>
						<%= link_to 'admin', '/admin' %>
					<% end %>
				<% else %>
					<%= link_to "Sign in", signin_path %>
					<%= link_to 'Sign up', signup_path %>
      <% end %>
			</nav>
		</header>

app/views/layouts/_stylesheets.html.erb
<%= csrf_meta_tag %>
		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
		<%= stylesheet_link_tag 'style', media: 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
			<%= yield %>
		<div class = 'clear'></div>
		<footer>
		
		</footer>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<section id = "con">
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>
</section>